version: '3'

services:

  cache-srv:
    image: registry.eshop.com/eshop/cache-srv:${TAG}
    container_name: cache-srv
    ports:
      - "7001:7001"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  ad-srv:
    image: registry.eshop.com/eshop/ad-srv:${TAG}
    container_name: ad-srv
    ports:
      - "8001:8001"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
  mall-srv:
    image: registry.eshop.com/eshop/mall-srv:${TAG}
    container_name: mall-srv
    ports:
      - "8002:8002"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  order-srv:
    image: registry.eshop.com/eshop/order-srv:${TAG}
    container_name: order-srv
    ports:
      - "8003:8003"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  product-srv:
    image: registry.eshop.com/eshop/product-srv:${TAG}
    container_name: product-srv
    ports:
      - "8004:8004"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  property-srv:
    image: registry.eshop.com/eshop/property-srv:${TAG}
    container_name: property-srv
    ports:
      - "8005:8005"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  user-srv:
    image: registry.eshop.com/eshop/user-srv:${TAG}
    container_name: user-srv
    ports:
      - "8006:8006"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  operator-srv:
    image: registry.eshop.com/eshop/operator-srv:${TAG}
    container_name: operator-srv
    ports:
      - "8007:8007"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  statistics-srv:
    image: registry.eshop.com/eshop/statistics-srv:${TAG}
    container_name: statistics-srv
    ports:
      - "8008:8008"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  member-api:
    image: registry.eshop.com/eshop/member-api:${TAG}
    container_name: member-api
    ports:
      - "1111:1111"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
          - /usr/local/eshop/media:/usr/local/eshop/media
    networks:
      - eshop_eshopNet
  merchant-api:
    image: registry.eshop.com/eshop/merchant-api:${TAG}
    container_name: merchant-api
    ports:
      - "2222:2222"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
          - /usr/local/eshop/media:/usr/local/eshop/media
    networks:
      - eshop_eshopNet
  operator-api:
    image: registry.eshop.com/eshop/operator-api:${TAG}
    container_name: operator-api
    ports:
      - "3333:3333"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
          - /usr/local/eshop/media:/usr/local/eshop/media
    networks:
      - eshop_eshopNet
  external-api:
    image: registry.eshop.com/eshop/external-api:${TAG}
    container_name: external-api
    ports:
      - "5555:5555"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet
  jobs:
    image: registry.eshop.com/eshop/jobs:${TAG}
    container_name: jobs
    ports:
      - "6666:6666"
    environment:
      - spring.cloud.config.profile=dev
      - spring.cloud.config.uri=http://192.168.1.29:8080
      - TZ=Asia/Shanghai
    volumes:
          - /etc/localtime:/etc/localtime:ro
    networks:
      - eshop_eshopNet

networks:
  eshop_eshopNet:
    external: true